

default_platform(:android)

platform :android do
  desc "distribute a new release build to firebase app distribution"
  lane :distribute do
    # sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    release = firebase_app_distribution(
            app: "1:461779055526:android:834e1269780a93afc11567",
            firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
            android_artifact_type: "APK",
            android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
            testers: "mohamed.eldawi@ejust.edu.eg, mohamed.hesham2174@gmail.com",
            release_notes: "First fastlane release of the app"
        )
  end
end
